name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "Ab3DAAIncDEwMmViMWQ4NTk3MDc0NGQ3YjliNGM0MTJmNGVjMjM5OXAxNDg1Nzk"
UPSTASH_REDIS_REST_URL = "https://absolute-burro-48579.upstash.io"